version: "3.3"

services:
  app:
    container_name: mainweb_frontend
    build:
      context: .
      dockerfile: dockerfile
    env_file:
      - .env.production
    networks:
      - nginx-proxy-net

networks:
  nginx-proxy-net:
    external: true
